#this is for laptop on the left side
monitor=eDP-1,1920x1080@144,0x0,1.25
monitor=HDMI-A-1,1920x1080@144,1536x0,1

#this is for laptop on right side
# monitor=HDMI-A-1,1920x1080@144,0x0,1
# monitor=eDP-1,1920x1080@144,1920x0,1.25

workspace=1, monitor:HDMI-A-1
workspace=2, monitor:HDMI-A-1
workspace=3, monitor:HDMI-A-1
workspace=4, monitor:eDP-1
workspace=5, monitor:eDP-1
